server:
  port: 8081

spring:
  application:
    name: Spring security with Keycloak

  ## keycloak
  security:
    oauth2:
      client:
        provider:
          xxxxxx:
            issuer-uri: http://localhost:8080/realms/sbilh

        registration:
          yyyyyy:
            provider: xxxxxx
            client-name: sbilh-client
            client-id: sbilh-client
            client-secret: UDb3sy3foq4zaahMoaQNk4sWQzagJxnb
            scope: openid,offline_access,profile
            authorization-grant-type: authorization_code
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sbilh